# Generated by Django 5.2.13 on 2026-04-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
